---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mehoussou/argocd_tuto_mc.git
    targetRevision: HEAD
    path: environments/staging/apps
  destination:
    server: https://kubernetes.default.svc
# added sync policy to automate the change from github to argocd without go to click on sync anytime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    